---
application:
  name: "programming-langugages-api"
  project: "Test1"
  organization: "QoveryCommunity"
routers:
- name: "main-programming-langugages-api"
  routes:
  - application_name: "programming-langugages-api"
    paths:
    - "/*"
